
services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.12.2
    container_name: forkwise-mlflow
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      MLFLOW_S3_ENDPOINT_URL: https://chi.tacc.chameleoncloud.org:7480
      AWS_ACCESS_KEY_ID: 8921c48faf83433db2b1439a9b2889fd
      AWS_SECRET_ACCESS_KEY: 7d1ce78efc5a48019888c9f3fa8ba2dd
    volumes:
      - mlflow-db:/mlflow/db
    command: >
      /bin/sh -c "pip install boto3 -q &&
      mlflow server
      --host 0.0.0.0
      --port 5000
      --backend-store-uri sqlite:////mlflow/db/mlflow.db
      --default-artifact-root s3://data-proj01/mlflow
      --artifacts-destination s3://data-proj01/mlflow"

volumes:
  mlflow-db:
