apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-generator
  namespace: forkwise-data
spec:
  replicas: 0
  selector:
    matchLabels:
      app: data-generator
  template:
    metadata:
      labels:
        app: data-generator
    spec:
      containers:
        - name: generator
          image: ghcr.io/itsnotaka/forkwise-generator:demo
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: forkwise-data-config
          env:
            - name: OS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-credentials
                  key: access-key
            - name: OS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-credentials
                  key: secret-key
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
